library(dplyr)
d <- read.csv('expower/household_power_consumption.txt',sep=';')
ds <- filter(d,Date=='1/2/2007' | Date=='2/2/2007')
par(mfrow=c(2,2))
gap <- as.numeric(as.character(ds$Global_active_power))
gap <- na.omit(gap)
dates <- unique(ds$Date)
dates <- as.Date(dates,"%d/%m/%Y")
wdays <- weekdays(dates)
wdays <- c(wdays, weekdays(as.Date(dates[length(dates)] + 1)))
t <- as.POSIXct(strptime(paste(ds$Date,ds$Time,sep=' '),"%d/%m/%Y %H:%M:%S"))
plot(t,gap,ylab='Global active power',type='n')
lines(t,gap)
axis(1, at=c(grep('00:00:00',t),length(t)),labels=wdays)
v <- as.numeric(as.character(ds$Voltage))
plot(t,v,type='n',ylab="Voltage",xlab='datetime')
lines(t,v)
plot(t,ds$Sub_metering_1,type='n',ylab='Sub metering')
lines(t,ds$Sub_metering_1)
lines(t,ds$Sub_metering_2,col='red')
lines(t,ds$Sub_metering_3,col='blue')
axis(1, at=c(grep('00:00:00',t),length(t)),labels=wdays)
legend("topright",legend=c("Sub metering 1","Sub metering 2","Sub metering 3"),col=c(1,2,4),lty=1)
rp <- as.numeric(as.character(ds$Global_reactive_power))
plot(t,rp,type='n',ylab='Global reactive power',xlab='datetime')
lines(t,rp)
