library(dplyr)
d <- read.csv('expower/household_power_consumption.txt',sep=';')
ds <- filter(d,Date=='1/2/2007' | Date=='2/2/2007')
gap <- as.numeric(as.character(ds$Global_active_power))
gap <- na.omit(gap)
dates <- unique(ds$Date)
dates <- as.Date(dates,"%d/%m/%Y")
wdays <- weekdays(dates)
wdays <- c(wdays, weekdays(as.Date(dates[length(dates)] + 1)))
xlabels <- character(length(ds$Time))
t <- as.POSIXct(strptime(paste(ds$Date,ds$Time,sep=' '),"%d/%m/%Y %H:%M:%S"))
plot(t,gap,ylab="Global active power (kilowatts)",type='n')
lines(t,gap)
axis(1, at=c(grep('00:00:00',t),length(t)),labels=wdays)